version: "2"

services:
  boilerplate-web-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boilerplate-web-api
    volumes:
    - ./:/code
    env_file:
      - .env.docker
    restart: unless-stopped
    command: >
        bash -c "flask run"
    ports:
      - "5324:5324"
    networks:
      - boilerplate-network


networks:
  boilerplate-network:
    driver: bridge
